<?php

namespace App\Models\Murabahah\Limac;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MurabahahLimacCapacity extends Model
{
    use HasFactory;

    protected $fillable = [
        'kode_pengajuan',
        'kode_nasabah',
        'nama_nasabah',

        // Data Rekening Nasabah
        'nama_bank_nasabah',
        'no_bank_account_nasabah',
        'tanggal_nasabah_bulan_1',
        'saldo_awal_nasabah_bulan_1',
        'total_debet_nasabah_bulan_1',
        'total_kredit_nasabah_bulan_1',
        'saldo_akhir_nasabah_bulan_1',
        'tanggal_nasabah_bulan_2',
        'saldo_awal_nasabah_bulan_2',
        'total_debet_nasabah_bulan_2',
        'total_kredit_nasabah_bulan_2',
        'saldo_akhir_nasabah_bulan_2',
        'tanggal_nasabah_bulan_3',
        'saldo_awal_nasabah_bulan_3',
        'total_debet_nasabah_bulan_3',
        'total_kredit_nasabah_bulan_3',
        'saldo_akhir_nasabah_bulan_3',

        // Data Rekening Pasangan
        'nama_bank_pasangan',
        'no_bank_account_pasangan',
        'tanggal_pasangan_bulan_1',
        'saldo_awal_pasangan_bulan_1',
        'total_debet_pasangan_bulan_1',
        'total_kredit_pasangan_bulan_1',
        'saldo_akhir_pasangan_bulan_1',
        'tanggal_pasangan_bulan_2',
        'saldo_awal_pasangan_bulan_2',
        'total_debet_pasangan_bulan_2',
        'total_kredit_pasangan_bulan_2',
        'saldo_akhir_pasangan_bulan_2',
        'tanggal_pasangan_bulan_3',
        'saldo_awal_pasangan_bulan_3',
        'total_debet_pasangan_bulan_3',
        'total_kredit_pasangan_bulan_3',
        'saldo_akhir_pasangan_bulan_3',

        'jenis_pinjaman_nasabah_1',
        'limit_nasabah_1',
        'jangka_waktu_nasabah_1',
        'sisa_hutang_nasabah_1',
        'kreditur_nasabah_1',
        'agunan_nasabah_1',
        'jenis_pinjaman_nasabah_2',
        'limit_nasabah_2',
        'jangka_waktu_nasabah_2',
        'sisa_hutang_nasabah_2',
        'kreditur_nasabah_2',
        'agunan_nasabah_2',
        'jenis_pinjaman_nasabah_3',
        'limit_nasabah_3',
        'jangka_waktu_nasabah_3',
        'sisa_hutang_nasabah_3',
        'kreditur_nasabah_3',
        'agunan_nasabah_3',
        'jenis_pinjaman_pasangan_1',
        'limit_pasangan_1',
        'jangka_waktu_pasangan_1',
        'sisa_hutang_pasangan_1',
        'kreditur_pasangan_1',
        'agunan_pasangan_1',
        'jenis_pinjaman_pasangan_2',
        'limit_pasangan_2',
        'jangka_waktu_pasangan_2',
        'sisa_hutang_pasangan_2',
        'kreditur_pasangan_2',
        'agunan_pasangan_2',
        'jenis_pinjaman_pasangan_3',
        'limit_pasangan_3',
        'jangka_waktu_pasangan_3',
        'sisa_hutang_pasangan_3',
        'kreditur_pasangan_3',
        'agunan_pasangan_3',

        'penghasilan_nasabah',
        'keterangan_penghasilan_nasabah',
        'penghasilan_pasangan',
        'keterangan_penghasilan_pasangan',
        'sumber_penghasilan_lain',
        'keterangan_sumber_penghasilan_lain',
        'biaya_sewa_rumah',
        'keterangan_biaya_sewa_rumah',
        'biaya_makan',
        'keterangan_biaya_makan',
        'biaya_transportasi',
        'keterangan_biaya_transportasi',
        'biaya_pendidikan',
        'keterangan_biaya_pendidikan',
        'biaya_listrik_air_gas',
        'keterangan_biaya_listrik_air_gas',
        'angsuran_pinjaman',
        'keterangan_angsuran_pinjaman',
        'premi_asuransi',
        'keterangan_premi_asuransi',
        'tabungan_berjangka',
        'keterangan_tabungan_berjangka',
        'pengeluaran_lain',
        'keterangan_pengeluaran_lain',

        'jangka_waktu_pembiayaan',

        'tempatkerja_kelokasi_bank',
        'tempatkerja_kelokasi_agunan',
        'pembayaran_kolektif',
        'pembayaran_nonkolektif',

        'username',
        'kode_tempat',
    ];
}
