<?php

namespace App\Models\Multiguna\Limac;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MultigunaLimacCapacity extends Model
{
    use HasFactory;

    protected $fillable = [
        'kode_pengajuan',
        'kode_nasabah',
        'nama_nasabah',

        'memiliki_jabatan_rangkap',
        'publik_figur',
        'pemegang_jabatan_tertinggi',
        'bukan_pemegang_jabatan_tertinggi',
        'non_jabatan',
        'mendapat_rumah_dinas',
        'mendapat_mobil_dinas',
        'mendapat_sepeda_motor_dinas',
        'mendapat_fasilitas_pinjaman_uang',
        'belum_mendapat_fasilitas_dinas',

        'nama_bank_nasabah',
        'no_bank_account_nasabah',
        'tanggal_nasabah_bulan_1',
        'saldo_awal_nasabah_bulan_1',
        'total_debet_nasabah_bulan_1',
        'total_kredit_nasabah_bulan_1',
        'saldo_akhir_nasabah_bulan_1',
        'tanggal_nasabah_bulan_2',
        'saldo_awal_nasabah_bulan_2',
        'total_debet_nasabah_bulan_2',
        'total_kredit_nasabah_bulan_2',
        'saldo_akhir_nasabah_bulan_2',
        'tanggal_nasabah_bulan_3',
        'saldo_awal_nasabah_bulan_3',
        'total_debet_nasabah_bulan_3',
        'total_kredit_nasabah_bulan_3',
        'saldo_akhir_nasabah_bulan_3',

        // Data Rekening Pasangan
        'nama_bank_pasangan',
        'no_bank_account_pasangan',
        'tanggal_pasangan_bulan_1',
        'saldo_awal_pasangan_bulan_1',
        'total_debet_pasangan_bulan_1',
        'total_kredit_pasangan_bulan_1',
        'saldo_akhir_pasangan_bulan_1',
        'tanggal_pasangan_bulan_2',
        'saldo_awal_pasangan_bulan_2',
        'total_debet_pasangan_bulan_2',
        'total_kredit_pasangan_bulan_2',
        'saldo_akhir_pasangan_bulan_2',
        'tanggal_pasangan_bulan_3',
        'saldo_awal_pasangan_bulan_3',
        'total_debet_pasangan_bulan_3',
        'total_kredit_pasangan_bulan_3',
        'saldo_akhir_pasangan_bulan_3',

        'jenis_pinjaman_nasabah_1',
        'limit_nasabah_1',
        'jangka_waktu_nasabah_1',
        'sisa_hutang_nasabah_1',
        'kreditur_nasabah_1',
        'agunan_nasabah_1',
        'jenis_pinjaman_nasabah_2',
        'limit_nasabah_2',
        'jangka_waktu_nasabah_2',
        'sisa_hutang_nasabah_2',
        'kreditur_nasabah_2',
        'agunan_nasabah_2',
        'jenis_pinjaman_nasabah_3',
        'limit_nasabah_3',
        'jangka_waktu_nasabah_3',
        'sisa_hutang_nasabah_3',
        'kreditur_nasabah_3',
        'agunan_nasabah_3',
        'jenis_pinjaman_pasangan_1',
        'limit_pasangan_1',
        'jangka_waktu_pasangan_1',
        'sisa_hutang_pasangan_1',
        'kreditur_pasangan_1',
        'agunan_pasangan_1',
        'jenis_pinjaman_pasangan_2',
        'limit_pasangan_2',
        'jangka_waktu_pasangan_2',
        'sisa_hutang_pasangan_2',
        'kreditur_pasangan_2',
        'agunan_pasangan_2',
        'jenis_pinjaman_pasangan_3',
        'limit_pasangan_3',
        'jangka_waktu_pasangan_3',
        'sisa_hutang_pasangan_3',
        'kreditur_pasangan_3',
        'agunan_pasangan_3',

        'gaji_pokok',
        'tunjangan_penghasilan',
        'tunjangan_kesejahteraan',
        'tunjangan_struktural',
        'tunjangan_fungsional',
        'tunjangan_suami_istri',
        'tunjangan_anak',
        'tunjangan_beras',
        'tunjangan_lain_lain',
        'tunjangan_pengobatan',
        'penerimaan_lain_lain',
        'simpanan_wajib',
        'iuran_koperasi',
        'iuran_bpjs',
        'potongan_lain_lain',
        'pajak_penghasilan_pph21',
        'angsuran_pinjaman_lain',

        'username',
        'kode_tempat',
    ];
}
